export const ACTION_GET_FLEETS = 'ACTION_GET_FLEETS';
export const ACTION_ADD_FLEET = 'ACTION_ADD_FLEET';
export const ACTION_UPDATE_FLEET = 'ACTION_UPDATE_FLEET';
export const ACTION_DELETE_FLEET = 'ACTION_DELETE_FLEET';
